# all: trab1

# trab1: tiny.o main.o
# 	   g++ -o tc1 tiny.o main.o

# tiny.o: tinyxml2.cpp
# 		g++ -o tinyxml2.o -c tinyxml2.cpp

# main.o: main.cpp tinyxml2.h
# 		g++ -o main.o -c main.cpp

# clean:
# 		rm -rf *.o


all:
	 g++ Circle.h Circle.cpp Scanner.h Scanner.cpp Window.h Window.cpp tinyxml2.cpp tinyxml2.h main.cpp -o trabalhocg -lGL -lGLU -lglut

clean:
		rm -rf *.o trabalhocg
