all:
	 g++ -std=c++11 -c Color.cpp  -o Color.o
	 g++ -std=c++11 -c Elipse.cpp  -o Elipse.o
	 g++ -std=c++11 -c Rectangle.cpp  -o Rectangle.o
	 g++ -std=c++11 -c Player.cpp  -o Player.o
	 g++ -std=c++11 -c Stadium.cpp  -o Stadium.o
	 g++ -std=c++11 -c Point.cpp  -o Point.o
	 g++ -std=c++11 -c Circle.cpp  -o Circle.o
	 g++ -std=c++11 -c Scanner.cpp -o Scanner.o
	 g++ -std=c++11 -c Window.cpp -o Window.o
	 g++ -std=c++11 -c tinyxml2.cpp -o Tiny.o
	 g++ -std=c++11 *.o main.cpp -o trabalhocg -lGL -lGLU -lglut 

clean:
		rm -rf *.o trabalhocg
