package protocolo;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Commands.proto

public final class CommandsProto {
  private CommandsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code CommandType}
   */
  public enum CommandType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>LS = 0;</code>
     */
    LS(0),
    /**
     * <code>CD = 1;</code>
     */
    CD(1),
    /**
     * <code>MV = 2;</code>
     */
    MV(2),
    /**
     * <code>MKDIR = 3;</code>
     */
    MKDIR(3),
    /**
     * <code>RMDIR = 4;</code>
     */
    RMDIR(4),
    /**
     * <code>RM = 5;</code>
     */
    RM(5),
    /**
     * <code>CP = 6;</code>
     */
    CP(6),
    /**
     * <code>CAT = 7;</code>
     */
    CAT(7),
    /**
     * <code>UPLOAD = 8;</code>
     */
    UPLOAD(8),
    /**
     * <code>DOWNLOAD = 9;</code>
     */
    DOWNLOAD(9),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>LS = 0;</code>
     */
    public static final int LS_VALUE = 0;
    /**
     * <code>CD = 1;</code>
     */
    public static final int CD_VALUE = 1;
    /**
     * <code>MV = 2;</code>
     */
    public static final int MV_VALUE = 2;
    /**
     * <code>MKDIR = 3;</code>
     */
    public static final int MKDIR_VALUE = 3;
    /**
     * <code>RMDIR = 4;</code>
     */
    public static final int RMDIR_VALUE = 4;
    /**
     * <code>RM = 5;</code>
     */
    public static final int RM_VALUE = 5;
    /**
     * <code>CP = 6;</code>
     */
    public static final int CP_VALUE = 6;
    
    /**
     * <code>CAT = 7;</code>
     */
    public static final int CAT_VALUE = 7;
    /**
     * <code>UPLOAD = 8;</code>
     */
    public static final int UPLOAD_VALUE = 8;
    /**
     * <code>DOWNLOAD = 9;</code>
     */
    public static final int DOWNLOAD_VALUE = 9;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static CommandType valueOf(int value) {
      return forNumber(value);
    }

    public static CommandType forNumber(int value) {
      switch (value) {
        case 0: return LS;
        case 1: return CD;
        case 2: return MV;
        case 3: return MKDIR;
        case 4: return RMDIR;
        case 5: return RM;
        case 6: return CP;
        case 7: return CAT;
        case 8: return UPLOAD;
        case 9: return DOWNLOAD;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<CommandType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        CommandType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<CommandType>() {
            public CommandType findValueByNumber(int number) {
              return CommandType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return CommandsProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final CommandType[] VALUES = values();

    public static CommandType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private CommandType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:CommandType)
  }

  /**
   * Protobuf enum {@code StatusCode}
   */
  public enum StatusCode
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>SUCCESS = 0;</code>
     */
    SUCCESS(0),
    /**
     * <code>ERR_PERMISS = 1;</code>
     */
    ERR_PERMISS(1),
    /**
     * <code>ERR_ARGS = 2;</code>
     */
    ERR_ARGS(2),
    /**
     * <code>ERR_DESC = 3;</code>
     */
    ERR_DESC(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>SUCCESS = 0;</code>
     */
    public static final int SUCCESS_VALUE = 0;
    /**
     * <code>ERR_PERMISS = 1;</code>
     */
    public static final int ERR_PERMISS_VALUE = 1;
    /**
     * <code>ERR_ARGS = 2;</code>
     */
    public static final int ERR_ARGS_VALUE = 2;
    /**
     * <code>ERR_DESC = 3;</code>
     */
    public static final int ERR_DESC_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static StatusCode valueOf(int value) {
      return forNumber(value);
    }

    public static StatusCode forNumber(int value) {
      switch (value) {
        case 0: return SUCCESS;
        case 1: return ERR_PERMISS;
        case 2: return ERR_ARGS;
        case 3: return ERR_DESC;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<StatusCode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        StatusCode> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<StatusCode>() {
            public StatusCode findValueByNumber(int number) {
              return StatusCode.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return CommandsProto.getDescriptor().getEnumTypes().get(1);
    }

    private static final StatusCode[] VALUES = values();

    public static StatusCode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private StatusCode(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:StatusCode)
  }

  public interface CommandOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Command)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .CommandType type = 1;</code>
     */
    int getTypeValue();
    /**
     * <code>optional .CommandType type = 1;</code>
     */
    CommandsProto.CommandType getType();

    /**
     * <code>optional string arg0 = 2;</code>
     */
    java.lang.String getArg0();
    /**
     * <code>optional string arg0 = 2;</code>
     */
    com.google.protobuf.ByteString
        getArg0Bytes();

    /**
     * <code>optional string arg1 = 3;</code>
     */
    java.lang.String getArg1();
    /**
     * <code>optional string arg1 = 3;</code>
     */
    com.google.protobuf.ByteString
        getArg1Bytes();

    /**
     * <code>optional bytes data = 4;</code>
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code Command}
   */
  public  static final class Command extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Command)
      CommandOrBuilder {
    // Use Command.newBuilder() to construct.
    private Command(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Command() {
      type_ = 0;
      arg0_ = "";
      arg1_ = "";
      data_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Command(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              arg0_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              arg1_ = s;
              break;
            }
            case 34: {

              data_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CommandsProto.internal_static_Command_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CommandsProto.internal_static_Command_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CommandsProto.Command.class, CommandsProto.Command.Builder.class);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>optional .CommandType type = 1;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>optional .CommandType type = 1;</code>
     */
    public CommandsProto.CommandType getType() {
      CommandsProto.CommandType result = CommandsProto.CommandType.valueOf(type_);
      return result == null ? CommandsProto.CommandType.UNRECOGNIZED : result;
    }

    public static final int ARG0_FIELD_NUMBER = 2;
    private volatile java.lang.Object arg0_;
    /**
     * <code>optional string arg0 = 2;</code>
     */
    public java.lang.String getArg0() {
      java.lang.Object ref = arg0_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        arg0_ = s;
        return s;
      }
    }
    /**
     * <code>optional string arg0 = 2;</code>
     */
    public com.google.protobuf.ByteString
        getArg0Bytes() {
      java.lang.Object ref = arg0_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        arg0_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ARG1_FIELD_NUMBER = 3;
    private volatile java.lang.Object arg1_;
    /**
     * <code>optional string arg1 = 3;</code>
     */
    public java.lang.String getArg1() {
      java.lang.Object ref = arg1_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        arg1_ = s;
        return s;
      }
    }
    /**
     * <code>optional string arg1 = 3;</code>
     */
    public com.google.protobuf.ByteString
        getArg1Bytes() {
      java.lang.Object ref = arg1_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        arg1_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATA_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>optional bytes data = 4;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != CommandsProto.CommandType.LS.getNumber()) {
        output.writeEnum(1, type_);
      }
      if (!getArg0Bytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, arg0_);
      }
      if (!getArg1Bytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, arg1_);
      }
      if (!data_.isEmpty()) {
        output.writeBytes(4, data_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != CommandsProto.CommandType.LS.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (!getArg0Bytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, arg0_);
      }
      if (!getArg1Bytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, arg1_);
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, data_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof CommandsProto.Command)) {
        return super.equals(obj);
      }
      CommandsProto.Command other = (CommandsProto.Command) obj;

      boolean result = true;
      result = result && type_ == other.type_;
      result = result && getArg0()
          .equals(other.getArg0());
      result = result && getArg1()
          .equals(other.getArg1());
      result = result && getData()
          .equals(other.getData());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + ARG0_FIELD_NUMBER;
      hash = (53 * hash) + getArg0().hashCode();
      hash = (37 * hash) + ARG1_FIELD_NUMBER;
      hash = (53 * hash) + getArg1().hashCode();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static CommandsProto.Command parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CommandsProto.Command parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CommandsProto.Command parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CommandsProto.Command parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CommandsProto.Command parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CommandsProto.Command parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static CommandsProto.Command parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static CommandsProto.Command parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static CommandsProto.Command parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CommandsProto.Command parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(CommandsProto.Command prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Command}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Command)
        CommandsProto.CommandOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CommandsProto.internal_static_Command_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CommandsProto.internal_static_Command_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CommandsProto.Command.class, CommandsProto.Command.Builder.class);
      }

      // Construct using CommandsProto.Command.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        type_ = 0;

        arg0_ = "";

        arg1_ = "";

        data_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CommandsProto.internal_static_Command_descriptor;
      }

      public CommandsProto.Command getDefaultInstanceForType() {
        return CommandsProto.Command.getDefaultInstance();
      }

      public CommandsProto.Command build() {
        CommandsProto.Command result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public CommandsProto.Command buildPartial() {
        CommandsProto.Command result = new CommandsProto.Command(this);
        result.type_ = type_;
        result.arg0_ = arg0_;
        result.arg1_ = arg1_;
        result.data_ = data_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CommandsProto.Command) {
          return mergeFrom((CommandsProto.Command)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CommandsProto.Command other) {
        if (other == CommandsProto.Command.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (!other.getArg0().isEmpty()) {
          arg0_ = other.arg0_;
          onChanged();
        }
        if (!other.getArg1().isEmpty()) {
          arg1_ = other.arg1_;
          onChanged();
        }
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        CommandsProto.Command parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (CommandsProto.Command) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int type_ = 0;
      /**
       * <code>optional .CommandType type = 1;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>optional .CommandType type = 1;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .CommandType type = 1;</code>
       */
      public CommandsProto.CommandType getType() {
        CommandsProto.CommandType result = CommandsProto.CommandType.valueOf(type_);
        return result == null ? CommandsProto.CommandType.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .CommandType type = 1;</code>
       */
      public Builder setType(CommandsProto.CommandType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .CommandType type = 1;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object arg0_ = "";
      /**
       * <code>optional string arg0 = 2;</code>
       */
      public java.lang.String getArg0() {
        java.lang.Object ref = arg0_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          arg0_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string arg0 = 2;</code>
       */
      public com.google.protobuf.ByteString
          getArg0Bytes() {
        java.lang.Object ref = arg0_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          arg0_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string arg0 = 2;</code>
       */
      public Builder setArg0(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        arg0_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string arg0 = 2;</code>
       */
      public Builder clearArg0() {
        
        arg0_ = getDefaultInstance().getArg0();
        onChanged();
        return this;
      }
      /**
       * <code>optional string arg0 = 2;</code>
       */
      public Builder setArg0Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        arg0_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object arg1_ = "";
      /**
       * <code>optional string arg1 = 3;</code>
       */
      public java.lang.String getArg1() {
        java.lang.Object ref = arg1_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          arg1_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string arg1 = 3;</code>
       */
      public com.google.protobuf.ByteString
          getArg1Bytes() {
        java.lang.Object ref = arg1_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          arg1_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string arg1 = 3;</code>
       */
      public Builder setArg1(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        arg1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string arg1 = 3;</code>
       */
      public Builder clearArg1() {
        
        arg1_ = getDefaultInstance().getArg1();
        onChanged();
        return this;
      }
      /**
       * <code>optional string arg1 = 3;</code>
       */
      public Builder setArg1Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        arg1_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes data = 4;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>optional bytes data = 4;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes data = 4;</code>
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Command)
    }

    // @@protoc_insertion_point(class_scope:Command)
    private static final CommandsProto.Command DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new CommandsProto.Command();
    }

    public static CommandsProto.Command getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Command>
        PARSER = new com.google.protobuf.AbstractParser<Command>() {
      public Command parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Command(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Command> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Command> getParserForType() {
      return PARSER;
    }

    public CommandsProto.Command getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .StatusCode statusCode = 1;</code>
     */
    int getStatusCodeValue();
    /**
     * <code>optional .StatusCode statusCode = 1;</code>
     */
    CommandsProto.StatusCode getStatusCode();

    /**
     * <code>optional bytes response = 2;</code>
     */
    com.google.protobuf.ByteString getResponse();
  }
  /**
   * Protobuf type {@code Response}
   */
  public  static final class Response extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Response)
      ResponseOrBuilder {
    // Use Response.newBuilder() to construct.
    private Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Response() {
      statusCode_ = 0;
      response_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              statusCode_ = rawValue;
              break;
            }
            case 18: {

              response_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CommandsProto.internal_static_Response_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CommandsProto.internal_static_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CommandsProto.Response.class, CommandsProto.Response.Builder.class);
    }

    public static final int STATUSCODE_FIELD_NUMBER = 1;
    private int statusCode_;
    /**
     * <code>optional .StatusCode statusCode = 1;</code>
     */
    public int getStatusCodeValue() {
      return statusCode_;
    }
    /**
     * <code>optional .StatusCode statusCode = 1;</code>
     */
    public CommandsProto.StatusCode getStatusCode() {
      CommandsProto.StatusCode result = CommandsProto.StatusCode.valueOf(statusCode_);
      return result == null ? CommandsProto.StatusCode.UNRECOGNIZED : result;
    }

    public static final int RESPONSE_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString response_;
    /**
     * <code>optional bytes response = 2;</code>
     */
    public com.google.protobuf.ByteString getResponse() {
      return response_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (statusCode_ != CommandsProto.StatusCode.SUCCESS.getNumber()) {
        output.writeEnum(1, statusCode_);
      }
      if (!response_.isEmpty()) {
        output.writeBytes(2, response_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (statusCode_ != CommandsProto.StatusCode.SUCCESS.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, statusCode_);
      }
      if (!response_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, response_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof CommandsProto.Response)) {
        return super.equals(obj);
      }
      CommandsProto.Response other = (CommandsProto.Response) obj;

      boolean result = true;
      result = result && statusCode_ == other.statusCode_;
      result = result && getResponse()
          .equals(other.getResponse());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + STATUSCODE_FIELD_NUMBER;
      hash = (53 * hash) + statusCode_;
      hash = (37 * hash) + RESPONSE_FIELD_NUMBER;
      hash = (53 * hash) + getResponse().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static CommandsProto.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CommandsProto.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CommandsProto.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CommandsProto.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CommandsProto.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CommandsProto.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static CommandsProto.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static CommandsProto.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static CommandsProto.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CommandsProto.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(CommandsProto.Response prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Response)
        CommandsProto.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CommandsProto.internal_static_Response_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CommandsProto.internal_static_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CommandsProto.Response.class, CommandsProto.Response.Builder.class);
      }

      // Construct using CommandsProto.Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        statusCode_ = 0;

        response_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CommandsProto.internal_static_Response_descriptor;
      }

      public CommandsProto.Response getDefaultInstanceForType() {
        return CommandsProto.Response.getDefaultInstance();
      }

      public CommandsProto.Response build() {
        CommandsProto.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public CommandsProto.Response buildPartial() {
        CommandsProto.Response result = new CommandsProto.Response(this);
        result.statusCode_ = statusCode_;
        result.response_ = response_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CommandsProto.Response) {
          return mergeFrom((CommandsProto.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CommandsProto.Response other) {
        if (other == CommandsProto.Response.getDefaultInstance()) return this;
        if (other.statusCode_ != 0) {
          setStatusCodeValue(other.getStatusCodeValue());
        }
        if (other.getResponse() != com.google.protobuf.ByteString.EMPTY) {
          setResponse(other.getResponse());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        CommandsProto.Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (CommandsProto.Response) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int statusCode_ = 0;
      /**
       * <code>optional .StatusCode statusCode = 1;</code>
       */
      public int getStatusCodeValue() {
        return statusCode_;
      }
      /**
       * <code>optional .StatusCode statusCode = 1;</code>
       */
      public Builder setStatusCodeValue(int value) {
        statusCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .StatusCode statusCode = 1;</code>
       */
      public CommandsProto.StatusCode getStatusCode() {
        CommandsProto.StatusCode result = CommandsProto.StatusCode.valueOf(statusCode_);
        return result == null ? CommandsProto.StatusCode.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .StatusCode statusCode = 1;</code>
       */
      public Builder setStatusCode(CommandsProto.StatusCode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        statusCode_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .StatusCode statusCode = 1;</code>
       */
      public Builder clearStatusCode() {
        
        statusCode_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString response_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes response = 2;</code>
       */
      public com.google.protobuf.ByteString getResponse() {
        return response_;
      }
      /**
       * <code>optional bytes response = 2;</code>
       */
      public Builder setResponse(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        response_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes response = 2;</code>
       */
      public Builder clearResponse() {
        
        response_ = getDefaultInstance().getResponse();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Response)
    }

    // @@protoc_insertion_point(class_scope:Response)
    private static final CommandsProto.Response DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new CommandsProto.Response();
    }

    public static CommandsProto.Response getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Response>
        PARSER = new com.google.protobuf.AbstractParser<Response>() {
      public Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Response(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Response> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Response> getParserForType() {
      return PARSER;
    }

    public CommandsProto.Response getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Command_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Command_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Response_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016Commands.proto\"O\n\007Command\022\032\n\004type\030\001 \001(" +
      "\0162\014.CommandType\022\014\n\004arg0\030\002 \001(\t\022\014\n\004arg1\030\003 " +
      "\001(\t\022\014\n\004data\030\004 \001(\014\"=\n\010Response\022\037\n\nstatusC" +
      "ode\030\001 \001(\0162\013.StatusCode\022\020\n\010response\030\002 \001(\014" +
      "*n\n\013CommandType\022\006\n\002LS\020\000\022\006\n\002CD\020\001\022\006\n\002MV\020\002\022" +
      "\t\n\005MKDIR\020\003\022\t\n\005RMDIR\020\004\022\006\n\002RM\020\005\022\006\n\002CP\020\006\022\007\n" +
      "\003CAT\020\007\022\n\n\006UPLOAD\020\010\022\014\n\010DOWNLOAD\020\t*F\n\nStat" +
      "usCode\022\013\n\007SUCCESS\020\000\022\017\n\013ERR_PERMISS\020\001\022\014\n\010" +
      "ERR_ARGS\020\002\022\014\n\010ERR_DESC\020\003B\017B\rCommandsProt" +
      "ob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Command_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Command_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Command_descriptor,
        new java.lang.String[] { "Type", "Arg0", "Arg1", "Data", });
    internal_static_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Response_descriptor,
        new java.lang.String[] { "StatusCode", "Response", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
